# Generated by Django 2.1.5 on 2019-05-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.CharField(max_length=50)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Meal')),
            ],
        ),
    ]
