# Generated by Django 2.1.5 on 2019-05-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal', to='meals.Meal'),
        ),
    ]
