# Generated by Django 2.1.5 on 2019-05-25 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190526_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Meal'),
        ),
    ]
